### ISSUE TITLE
Revenant's Missile attack skips A_FaceTarget

### ISSUE THREAD

**Issue by m-x-d** [davidxn/BDLite#1]
https://github.com/davidxn/BDLite/blob/d86eaae5ccfd5a6fe98313487accacda421432e7/pk3/decorate/monsters/Revenant.txt#L44

This skips both A_FaceTarget frames, which can result in Revenant firing missiles from his back. Should probably be "A_Jump(200, 3)".

**Comment by davidxn** [comment]
Fixed - thanks for your changes!
