### ISSUE TITLE
RevenantBalls is slower than in Vanilla / BD21

### ISSUE THREAD

**Issue by m-x-d** [davidxn/BDLite#2]
https://github.com/davidxn/BDLite/blob/d86eaae5ccfd5a6fe98313487accacda421432e7/pk3/decorate/monsters/MonsterProjectiles.txt#L622

Revenant's seeker missile speed is 10 in both [gzdoom.pk3](https://zdoom.org/wiki/Classes:RevenantTracer) and brutalv21.pk3. Was this change intentional?

**Comment by davidxn** [comment]
Fixed - thanks for your changes!
