### ISSUE TITLE
Cyberdemon's increased height causes map bugs

### ISSUE THREAD

**Issue by m-x-d** [davidxn/BDLite#3]
https://github.com/davidxn/BDLite/blob/d86eaae5ccfd5a6fe98313487accacda421432e7/pk3/decorate/monsters/Cyberdemon.txt#L12

While this change seems logical, it also causes quite a lot of vanilla wads to work incorrectly. For example, in Jimmy's [Deathless](https://www.doomworld.com/idgames/levels/doom/Ports/megawads/deathless) E1M9 the Cyberdemon is spawned in a 136-height sector (so Cyberdemon's HeightOK check passes), but is supposed to enter a 128-height door, which never happens in BDLite.

Keeping the height at vanilla value (110), but still doing the sprite scaling seems like a relatively reasonable compromise.

**Comment by davidxn** [comment]
@m-x-d Thanks so much for your work on this and the other changes you've been making! Are they in a place where I could start pulling them into the upstream?

**Comment by m-x-d** [comment]
Well, you can use [my fork](https://github.com/m-x-d/BDLite) as a reference. Right now it's not in a stable/tested state though.

**Comment by davidxn** [comment]
Thank you! Cherry-picked and incorporated many of your changes into master :)
